package truequear.domain.enumeration;

/**
 * The TipoObjetos enumeration.
 */
public enum TipoObjetos {
    ALIMENTACIONBEBIDA, ARTEANTIGUEDADE, VEHICULO, CASAHOGA, COLECCIONES, DEPORTE, EDUCAR, IMAGENESSONIDO, INFORMATICAEELECTRONICA, INMOBILIARIAS, JOYERIAS, JUEGOSJUGUETE, LIBROSREVISTASCOMIC, MUSICAX, ROPAYCALZADO, SALUDYBELLEZA, SERVICIOS, MANODEOBRA, TELEFONIAS, TIEMPOLIBRES
}
